repos:
    - repo: local
      hooks:
          - id: black
            name: black
            entry: black .
            language: system
            types: [ python ]

          - id: flake8
            name: flake8
            entry: flake8 lume tests
            language: system
            types: [ python ]

          - id: isort
            name: isort
            entry: isort .
            language: system
            types: [ python ]