site_name: lume
site_description: 🔥 Lume helps you with your daily dev operations and ease the CI & CD process.
strict: true
site_url: https://github.com/alice-biometrics/lume

theme:
  name: 'material'
  custom_dir: 'docs/theme'
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: blue
    accent: blue
    toggle:
      icon: material/lightbulb-outline
      name: "Switch to dark mode"
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: blue
    accent: blue
    toggle:
      icon: material/lightbulb
      name: "Switch to light mode"
  features:
    - content.tabs.link
  logo: 'logo-white.png'
  favicon: 'favicon.png'

repo_name: alice-biometrics/lume
repo_url: https://github.com/alice-biometrics/lume
edit_uri: edit/main/docs/

extra_css:
- 'css/terminal.css'
- 'css/tweaks.css'
- 'css/termynal.css'
- 'css/custom.css'
extra_javascript:
- 'js/redirects.js'
- 'js/ad.js'
- 'js/termynal.js'
- 'js/custom.js'

nav:
- Overview: index.md
- install.md
- getting_started.md
- features.md
- GitHub Actions: github_actions.md
- Contributing to lume: contributing.md
- changelog.md
- acknowledgements.md

markdown_extensions:
  - tables
  - markdown_include.include:
      base_path: docs
  - toc:
      permalink: true
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - mdx_truly_sane_lists

plugins:
- search
- exclude:
    glob:
    - _build/*
    - build/*
    - requirements/*

extra:
  social:
  - icon: fontawesome/brands/github-alt
    link: https://github.com/alice-biometrics/lume
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/alicebiometrics
  - icon: fontawesome/brands/linkedin
    link: https://www.linkedin.com/company/alicebiometrics