name: Bug
description: Ask about a problem
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        The `lume ðŸ”¥` community is glad to see you here. Your help is greatly appreciated.
        
        Please follow these instructions, fill every question, and do every step. ðŸ™
        
        This will help lume ðŸ”¥` community to add new features, fix bug, review pull requests, etc.

  - type: checkboxes
    id: checks
    attributes:
      label: First Check
      description: Please confirm and check all the following options.
      options:
        - label: I added a very descriptive title to this issue.
          required: true
        - label: I used the GitHub search to find a similar issue and didn't find it.
          required: true
        - label: I already read and followed all the [documentation](https://alice-biometrics.github.io/lume/) and didn't find an answer.
          required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        What is the problem, question, or error?

        Write a short description telling me what you are doing, what you expect to happen, and what is currently happening.
      placeholder: |
        * I expected a behavior using an installation step but I got ... whatever..
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you on?
      multiple: true
      options:
        - Linux
        - Windows
        - macOS
        - Other
    validations:
      required: true
  - type: textarea
    id: os-details
    attributes:
      label: Operating System Details
      description: You can add more details about your operating system here, in particular if you chose "Other".
  - type: input
    id: lume-version
    attributes:
      label: lume Version
      description: |
        What lume version are you using?

        You can find the lume version with:

        ```bash
        >> lume --version
        ```
    validations:
      required: true
  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: |
        What Python version are you using?

        You can find the Python version with:

        ```bash
        python --version
        ```
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any additional context information or screenshots you think are useful.
