name: ci

on:
  pull_request:
    paths-ignore:
      - '*.md'
      - 'lume/VERSION'
    branches: 
      - main

jobs:
  ci:

    strategy:
      max-parallel: 4
      matrix:
        os: [macOS-latest, ubuntu-latest]
        python-version: [3.7, 3.8, 3.9]
    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - uses: actions/cache@v2
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}-${{ hashFiles('requirements.txt') }}-${{ hashFiles('dev-requirements.txt') }}
    - name: Install
      run: |
        pip install -e .
        lume -install
    - name: Lint
      run: lume -lint
    - name: Static Analysis
      run: lume -static-analysis
    - name: Tests
      run: lume -test
    - name: Check Installation (--no-binary)
      run: lume -check-no-binary-installation
    - name: End2end test
      env:
        LUME_CONFIG_FILENAME: examples/lume-sample.yml
      run: lume -install -all
    - name: End2end test (OS-Specific Commands)
      env:
        LUME_CONFIG_FILENAME: examples/lume-sample-os-command-specific.yml
      run: lume -install -all
    - name: End2end test (Required env - internal)
      env:
        LUME_CONFIG_FILENAME: examples/lume-required-env-with-env.yml
      run: lume -install -all
    - name: End2end test (Required env - external)
      env:
        LUME_CONFIG_FILENAME: examples/lume-required-env-without-env.yml
        MY_NON_EXPECTED_REQUIRED_ENV: VALUE
      run: lume -install -all
    - name: End2end test (Required env - fails)
      env:
        LUME_CONFIG_FILENAME: examples/lume-required-env-without-env.yml
      run: lume -install -all | true
    - name: End2end test (Error syntax - fails)
      env:
        LUME_CONFIG_FILENAME: examples/lume-sample-with-syntax-error.yml
      run: lume -job | true

