name: coverage

on:
  push:
    paths-ignore:
      - '*.md'
      - 'lume/VERSION'
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
        cache-dependency-path: '**/*requirements.txt'
    - name: Install dependencies
      run: |
        pip install -e .
        lume -install
    - name: Coverage
      run: lume -coverage
    - uses: codecov/codecov-action@v3
      with:
        files: output/coverage/cobertura_coverage.xml
        name: lume
        fail_ci_if_error: true
